export const INIT_HOME_BANNER = 'INIT_HOME_BANNER'
export const INIT_HOME_CHANNEL = 'INIT_HOME_CHANNEL'
export const INIT_HOME_BRANDLIST = 'INIT_HOME_BRANDLIST'
export const INIT_HOME_NEWGOODLIST = 'INIT_HOME_NEWGOODLIST'
export const INIT_HOME_HOTGOODLIST = 'INIT_HOME_HOTGOODLIST'
export const INIT_HOME_CATEGORYLIST = 'INIT_HOME_CATEGORYLIST'
export const INIT_CATEGORY_CURRENT='INIT_CATEGORY_CURRENT'

